const dl = document.createElement('dl');
const dt1 = document.createElement('dt');
dt1.innerText = 'Term 1';
const dd1 = document.createElement('dd');
dd1.innerText = 'Description 1';
const dt2 = document.createElement('dt');
dt2.innerText = 'Term 2';
const dd2 = document.createElement('dd');
dd2.innerText = 'Description 2';
const dt3 = document.createElement('dt');
dt3.innerText = 'Term 3';
const dd3 = document.createElement('dd');
dd3.innerText = 'Description 3';
dl.appendChild(dt1);
dl.appendChild(dd1);
dl.appendChild(dt2);
dl.appendChild(dd2);
dl.appendChild(dt3);
dl.appendChild(dd3);
document.body.appendChild(dl);
